talerbank/app/urls.py
#  This file is part of TALER
#  (C) 2014, 2015, 2016 INRIA
#
#  TALER is free software; you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation; either version 3, or
# (at your option) any later version.
#
#  TALER is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
#  You should have received a copy of the GNU General Public
# License along with TALER; see the file COPYING.  If not, see
# <http://www.gnu.org/licenses/>.
#
#  @author Marcello Stanisci

from django.conf.urls import include, url
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^', include('talerbank.urls')),
    url(r'^$', RedirectView.as_view(pattern_name="profile"),
        name="index"),
    url(r'^favicon\.ico$', views.ignore),
    url(r'^admin/add/incoming$', views.add_incoming,
        name="add-incoming"),
    url(r'^login/$',
        auth_views.LoginView.as_view(
            template_name="login.html",
            authentication_form=views.TalerAuthenticationForm),
        name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^accounts/register/$', views.register, name="register"),
    url(r'^profile$', views.profile_page, name="profile"),
    url(r'^history$', views.serve_history, name="history"),
    url(r'^reject$', views.reject, name="reject"),
    url(r'^withdraw$', views.withdraw_nojs, name="withdraw-nojs"),
    url(r'^public-accounts$', views.serve_public_accounts,
        name="public-accounts"),
    url(r'^public-accounts/(?P<name>[a-zA-Z0-9]+)$',
        views.serve_public_accounts,
        name="public-accounts"),
    url(r'^public-accounts/(?P<name>[a-zA-Z0-9]+)/(?P<page>[0-9]+)$',
        views.serve_public_accounts,
        name="public-accounts"),
    url(r'^pin/question$', views.pin_tan_question,
        name="pin-question"),
    url(r'^pin/verify$', views.pin_tan_verify, name="pin-verify"),
    ]

talerbank/app/views.py
##
# This file is part of TALER
# (C) 2014, 2015, 2016 INRIA
#
# TALER is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation; either version 3, or
# (at your option) any later version. TALER is distributed in the
# hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
#  You should have received a copy of the GNU General Public
# License along with TALER; see the file COPYING.  If not, see
# <http://www.gnu.org/licenses/>
#
#  @author Marcello Stanisci
#  @author Florian Dold

from functools import wraps
import math
import json
import logging
import hashlib
import random
import re
import django.contrib.auth
import django.contrib.auth.views
import django.contrib.auth.forms
from django.db import transaction
from django import forms
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET
from django.views.decorators.http import require_http_methods
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from .models import BankAccount, BankTransaction
from .amount import Amount
from .schemas import validate_data
LOGGER = logging.getLogger(__name__)

##
# Constant value for the biggest number the bank handles.
# This value is just equal to the biggest number that JavaScript
# can handle (because of the wallet).
UINT64_MAX = (2**64) - 1


##
# Exception raised upon failing login.
#
class LoginFailed(Exception):
    hint = "Wrong username/password"
    http_status_code = 401

##
# Exception raised when the public history from
# a ordinary user account is tried to be accessed.
class PrivateAccountException(Exception):
    hint = "The selected account is private"
    http_status_code = 402


##
# Exception raised when some financial operation goes
# beyond the limit threshold.
class DebitLimitException(Exception):
    hint = "Debit too high, operation forbidden."
    http_status_code = 403

##
# Exception raised when some financial operation is
# attempted and both parties are the same account number.
#
class SameAccountException(Exception):
    hint = "Debit and credit account are the same."
    http_status_code = 403

##
# Exception raised when someone tries to reject a
# transaction, but they have no rights to accomplish
# such operation.
class RejectNoRightsException(Exception):
    hint = "You weren't the transaction credit account, " \
           "no rights to reject."
    http_status_code = 403

##
# The authentication for users to log in the bank.
#
class TalerAuthenticationForm(
        django.contrib.auth.forms.AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].widget.attrs["autofocus"] = True
        self.fields["username"].widget.attrs["placeholder"] = "Username"
        self.fields["password"].widget.attrs["placeholder"] = "Password"

##
# Return a empty response.  Used in "/favicon.ico" requests.
#
def ignore(request):
    del request
    return HttpResponse()

##
# Get a flag from the session and clear it.
#
# @param request the HTTP request being served.
# @param name name of the session value that should be retrieved.
# @return the value, if found; otherwise False.
def get_session_flag(request, name):
    if name in request.session:
        ret = request.session[name]
        del request.session[name]
        return ret
    return False


##
# Get a hint from the session and clear it.  A 'hint' is a
# "message" that different parts of the bank can send to each
# other - via the state - communicating what is the state of
# the HTTP session.
#
# @param request the HTTP request being served.
# @param name hint name
# @return the hint (a "null" one if none was found)
def get_session_hint(request, name):
    if name in request.session:
        ret = request.session[name]
        del request.session[name]
        return ret
    # Fail message, success message, hint.
    return False, False, None


##
# Build the list containing all the predefined accounts; the
# list contains, for example, the exchange, the bank itself, and
# all the public accounts (like GNUnet / Tor / FSF / ..)
def predefined_accounts_list():
    account = 2
    ret = []
    for i in settings.TALER_PREDEFINED_ACCOUNTS[1:]:
        ret.append((account, "%s (#%d)" % (i, account)))
        account += 1
    return ret

##
# Thanks to [1], this class provides a dropdown menu that
# can be used within a <select> element, in a <form>.
class InputDatalist(forms.TextInput):

    ##
    # Constructor function.
    #
    # @param self the object itself.
    # @param datalist a list of admitted values.
    # @param name the name of the value that will be sent
    #        along the POST.
    # @param args positional arguments
    # @param kwargs keyword arguments
    # @return the object
    def __init__(self, datalist, name, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._name = name
        self._datalist = datalist()
        self.attrs.update(
            {"list": "%slist" % name,
             "pattern": "[1-9]+[0-9]*"})

    ##
    # Method that produces the final HTML from the object itself.
    #
    # @param self the object itself
    # @param name the name of the value that will be sent
    #        along the POST
    # @param value value to be sent along the @a name.
    # @param attrs a dict indicating which HTML attribtues should
    #        be defined in the rendered element.
    # @param renderer render engine (left as None, typically); it
    #        is a class that respects the low-level render API from
    #        Django, see [2]
    def render(self, name, value, attrs=None, renderer=None):
        html = super().render(
            name, value, attrs=attrs, renderer=renderer)
        datalist = '<datalist id="%slist">' % self._name
        for dl_value, dl_text in self._datalist:
            datalist += '<option value="%s">%s</option>' \
                % (dl_value, dl_text)
        datalist += "</datalist>"
        return html + datalist


##
# Form for sending wire transfers.  It usually appears in the
# user profile page.
#
class WTForm(forms.Form):
    amount = forms.FloatField(
        min_value=0.1,
        widget=forms.NumberInput(attrs={"class": "currency-input"}))
    receiver = forms.IntegerField(
        min_value=1,
        widget=InputDatalist(predefined_accounts_list, "receiver"))
    subject = forms.CharField()



##
# This method serves the profile page, which is the main
# page where the user interacts with the bank, and also the
# page that the user gets after a successful login.  It has
# to handle the following cases: (1) the user requests the
# profile page after haing POSTed a wire transfer request.
# (2) The user requests the page after having withdrawn coins,
# that means that a wire transfer has been issued to the exchange.
# In this latter case, the method has to notify the wallet about
# the operation outcome.  (3) Ordinary GET case, where the
# straight page should be returned.
# 
# @param request Django-specific HTTP request object.
# @return Django-specific HTTP response object.
@login_required
def profile_page(request):
    if request.method == "POST":
        # WTForm ~ Wire Transfer Form.
        wtf = WTForm(request.POST)
        if wtf.is_valid():
            amount_parts = (settings.TALER_CURRENCY,
                            wtf.cleaned_data.get("amount") + 0.0)
            wire_transfer(
                Amount.parse("%s:%s" % amount_parts),
                BankAccount.objects.get(user=request.user),
                BankAccount.objects.get(account_no=wtf.cleaned_data.get("receiver")),
                wtf.cleaned_data.get("subject"))
            request.session["profile_hint"] = False, True, "Wire transfer successful!"
            return redirect("profile")
    wtf = WTForm()
    fail_message, success_message, hint = get_session_hint(request, "profile_hint")
    context = dict(
        name=request.user.username,
        balance=request.user.bankaccount.amount.stringify(
            settings.TALER_DIGITS, pretty=True),
        sign="-" if request.user.bankaccount.debit else "",
        fail_message=fail_message,
        success_message=success_message,
        hint=hint,
        precision=settings.TALER_DIGITS,
        currency=request.user.bankaccount.amount.currency,
        account_no=request.user.bankaccount.account_no,
        wt_form=wtf,
        history=extract_history(request.user.bankaccount,
                                True),
    )
    if settings.TALER_SUGGESTED_EXCHANGE:
        context["suggested_exchange"] = settings.TALER_SUGGESTED_EXCHANGE

    response = render(request, "profile_page.html", context)
    if "just_withdrawn" in request.session:
        del request.session["just_withdrawn"]
        response["X-Taler-Operation"] = "confirm-reserve"
        response["X-Taler-Reserve-Pub"] = request.session.get(
            "reserve_pub")
        response.status_code = 202
    return response


##
# Helper function that hashes its input.  Usually
# used to hash the response to the math CAPTCHA.
#
# @param ans the plain text answer to hash.
# @return the hashed version of @a ans.
def hash_answer(ans):
    hasher = hashlib.new("sha1")
    hasher.update(settings.SECRET_KEY.encode("utf-8"))
    hasher.update(ans.encode("utf-8"))
    return hasher.hexdigest()


##
# Helper function that makes CAPTCHA's question and
# answer pair.
#
# @return the question and (hashed) answer pair.
def make_question():

talerbank/app/templates/account_disabled.html
{% extends "base.html" %}

{% block headermsg %}
  <h1 class="nav">Account disabled<h1>
{% endblock headermsg %}
{% block content %}
  <aside class="sidebar" id="left">
  </aside>
  <section id="main">
    <article>
      <h1>Account disabled</h1>
      <p>{{ name }}, your account has been disabled, <a href="{% url("register") %}">register</a>
          a new one!</p>
    </article>
  </section>
{% endblock content %}

talerbank/app/templates/base.html
<!doctype html>
<!--
  This file is part of GNU TALER.
  Copyright (C) 2014, 2015, 2016 INRIA

  TALER is free software; you can redistribute it and/or modify it under the
  terms of the GNU Lesser General Public License as published by the Free Software
  Foundation; either version 2.1, or (at your option) any later version.

  TALER is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
  A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License along with
  TALER; see the file COPYING.  If not, see <http://www.gnu.org/licenses/>

  @author Marcello Stanisci
  @author Florian Dold
-->

<html data-taler-nojs="true">
  <head>
    <title>{{ settings_value("TALER_CURRENCY") }} Bank - Taler Demo</title>
    <link rel="stylesheet" type="text/css" href="{{ static('pure.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ static('web-common/demo.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ static('web-common/taler-fallback.css') }}" id="taler-presence-stylesheet" />
    <link rel="stylesheet" type="text/css" href="{{ static('bank.css') }}" />
    {% block head %} {% endblock %}
  </head>
  <body>
    <div class="demobar">
      <h1><span class="tt adorn-brackets">Taler Demo</span></h1>
      <h1><span class="it"><a href="{{ url('index') }}">Bank</a></span></h1>
      <p>This part of the demo shows how a bank that supports Taler directly would work.  In addition to
      using your own bank account, you can also see the transaction history of some <a href="{{ url('public-accounts') }}">Public Accounts</a>.</p>
      <p>Other parts of the demo:</p>
      <ul>
        <li><a href="{{ env('TALER_ENV_URL_INTRO', '#') }}">Introduction</a></li>
        <li><a href="{{ env('TALER_ENV_URL_BANK', '#') }}">Bank</a></li>
        <li><a href="{{ env('TALER_ENV_URL_MERCHANT_BLOG', '#') }}">Essay Shop</a></li>
        <li><a href="{{ env('TALER_ENV_URL_MERCHANT_DONATIONS', '#') }}">Donations</a></li>
        <li><a href="{{ env('TALER_ENV_URL_MERCHANT_SURVEY', '#') }}">Tipping/Survey</a></li>
        <li><a href="{{ env('TALER_ENV_URL_BACKOFFICE', '#') }}">Back-office</a></li>
      </ul>
      <p>You can learn more about Taler on our main <a href="https://taler.net">website</a>.</p>
    </div>
    <div class="content">
      {% block headermsg %} {% endblock %}
      {% block content %} {% endblock %}
      <div>
        <p>NOTE: the bank runs completely JavaScript-free.</p>
      </div>
    </div>
  </body>
</html>

talerbank/app/templates/error_exchange.html
<!DOCTYPE html>
<!--
  This file is part of GNU TALER.
  Copyright (C) 2014, 2015, 2016 INRIA

  TALER is free software; you can redistribute it and/or modify it under the
  terms of the GNU Lesser General Public License as published by the Free Software
  Foundation; either version 2.1, or (at your option) any later version.

  TALER is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
  A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License along with
  TALER; see the file COPYING.  If not, see <http://www.gnu.org/licenses/>

  @author Marcello Stanisci
  @author Florian Dold
-->
{% extends "base.html" %}

{% block headermsg %}
  <h1>Error</h1>
{% endblock headermsg %}
{% block content %}
  <aside class="sidebar" id="left">
  </aside>
  <section id="main">
    <article>
      <p>
      {{ message }}
      </p>
      <p>
      Status: {{ response_status }}
      </p>
      <p>
      Response body:
      <pre>{{ response_text }}</pre>
      </p>
    </article>
  </section>
{% endblock content %}

talerbank/app/templates/login.html
{% extends "base.html" %}
{#
  This file is part of GNU TALER.
  Copyright (C) 2014, 2015, 2016 INRIA

  TALER is free software; you can redistribute it and/or modify it under the
  terms of the GNU Lesser General Public License as published by the Free Software
  Foundation; either version 2.1, or (at your option) any later version.

  TALER is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
  A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License along with
  TALER; see the file COPYING.  If not, see <http://www.gnu.org/licenses/>

  @author Marcello Stanisci
  @author Florian Dold
#}

{% block headermsg %}
  <h1 class="nav">Welcome to the {{ settings_value("TALER_CURRENCY") }} Bank!</h1>
{% endblock headermsg %}

{% block content %}
  <section id="main">
    <article>
      <div class="login-form">
        <h2>Please login!</h2>
        <form method="post" class="pure-form" action="{{ url('login') }}">
          <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
          {{ form.username }}
          <input type="password" name="password" placeholder="password" />
          <input type="submit" value="login" class="pure-button pure-button-primary" />
          <input type="hidden" name="next" value="{{ next }}" />
        </form>
      </div>
      <p>
      If you are a new customer, please <a href="{{ url('register') }}">register</a>.
      Registration is fast and gratis, and it gives you a registration bonus
      of 100 {{ settings_value("TALER_CURRENCY") }}!
      </p>
      <p>
      To view transactions of public accounts,
      please <a href="{{ url('public-accounts') }}">click here</a>.
      </p>
    </article>
  </section>
{% endblock content %}

talerbank/app/templates/pin_tan.html
<!DOCTYPE html>
<!-- 
  This file is part of GNU TALER.
  Copyright (C) 2014, 2015, 2016 INRIA

  TALER is free software; you can redistribute it and/or modify it under the
  terms of the GNU Lesser General Public License as published by the Free Software
  Foundation; either version 2.1, or (at your option) any later version.

  TALER is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
  A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License along with
  TALER; see the file COPYING.  If not, see <http://www.gnu.org/licenses/>

  @author Marcello Stanisci
-->

{% extends "base.html" %}

{% block headermsg %}
  <h1 class="nav">PIN/TAN:  Confirm transaction</h1>
{% endblock %}

{% block content %}
  {% if fail_message %}
  <p class="informational informational-fail">
    {{ hint }}
  </p>
  {% endif %}
  <p>
    {{ settings_value("TALER_CURRENCY") }} Bank needs to verify that you
    intend to withdraw <b>{{ amount }}</b> from
    <b>{{ exchange }}</b>.
    To prove that you are the account owner, please answer the
    following &quot;security question&quot; (*):
  </p>
  <p>
    What is {{ question }} ?
  </p>
  <form method="post" action="{{ url('pin-verify') }}" class="pure-form">
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
    <input type="text" name="pin_0" value="" autocomplete="off" autofocus />
    <input type="hidden" name="pin_1" value="{{ hashed_answer }}" />
    <input type="hidden" name="question_url" value="{{ request.get_full_path() }}" />
    <input type="submit" value="Ok" class="pure-button pure-button-primary" />
  </form>
  <small style="margin: 40px 0px">(*) A real bank should ask for
    a PIN/TAN instead of a simple calculation. For example by sending
    a one time password to the customer's mobile or providing her a
    random password generator.
  <small>
{% endblock content %}

talerbank/app/templates/profile_page.html
{% extends "base.html" %}
{#
  This file is part of GNU TALER.
  Copyright (C) 2014, 2015, 2016 INRIA

  TALER is free software; you can redistribute it and/or modify it under the
  terms of the GNU Lesser General Public License as published by the Free Software
  Foundation; either version 2.1, or (at your option) any later version.

  TALER is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
  A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License along with
  TALER; see the file COPYING.  If not, see <http://www.gnu.org/licenses/>

  @author Marcello Stanisci
#}

{% block head %}
  <meta name="currency" value="{{ currency }}">
  <meta name="precision" value="{{ precision }}">
  <meta name="callback-url" value="{{ url('pin-question') }}">
  {% if withdraw and withdraw == "success" %}
    <meta name="reserve-pub" value="{{ reserve_pub }}">
  {% endif %}
  {% if suggested_exchange %}
    <meta name="suggested-exchange" value="{{ suggested_exchange }}">
  {% endif %}
  <link rel="stylesheet" type="text/css" href="{{ static('disabled-button.css') }}">
{% endblock head %}
{% block headermsg %}
  <div>
    <h1 class="nav">Welcome <em>{{ name }}</em>!</h1>
    <a href="{{ url('logout') }}" class="pure-button">[Logout]</a><br>
  </div>
{% endblock headermsg %}
{% block content %}
  <section id="menu">
    <p>Account: # {{ account_no }}</p>
    <p>Current balance: <b>{{ sign }} {{ balance }}</b></p>
  </section>
  <section id="main">
    <article>
      {% if fail_message %}
        <div class="notification">
          <p class="informational informational-fail">
            {{ hint }}
          </p>
        </div>
      {% endif %}
      {% if success_message %}
        <div class="notification">
          <p class="informational informational-ok">
            {{ hint }}
          </p>
        </div>
        {% endif %}
    </article>
    <article>
      <div class="taler-installed-hide">
        <h2>Wallet not installed!</h2>
        You need to install the Taler wallet to withdraw digital coins.
         <span id="install-done" style="visibility: hidden">(done)</span>
         <ul>
           <li>from the app store for <a
               href="https://chrome.google.com/webstore/detail/gnu-taler-wallet/millncjiddlpgdmkklmhfadpacifaonc">Google
               Chrome and Chromium</a>
           </li>
           <li>By visiting our <a href="/landing">landing page</a>.
           </li>
         </UL>
        Right now, you need Chrome or Chromium to
        install the wallet. We plan to support other browsers in the future.
      </div>

      <div>
        <h2>Withdraw digital coins using Taler</h2>

        <form id="reserve-form"
              class="pure-form"
              action="{{ url('withdraw-nojs') }}"
              method="post"
              name="tform">
          <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
          Amount to withdraw:
          <select id="reserve-amount" name="kudos_amount" class="amount" autofocus>
              <option value="{{ currency }}:5.00">5.00</option>
              <option value="{{ currency }}:10.00">10.00</option>
              <option value="{{ currency }}:15.00">15.00</option>
              <option value="{{ currency }}:20.00">20.00</option>
          </select><!--
            --><input type="text" readonly class="currency-indicator" size="{{ currency|length }}" tabindex="-1" value="{{ currency }}">

          <input id="select-exchange"
                 class="taler-installed-show pure-button pure-button-primary"
                 type="submit"
                 value="Select exchange provider" />
          <br />
          <br />
          <input class="taler-installed-hide pure-button pure-button-primary"
                 type="button"
                 disabled
                 value="Select exchange provider" />
        </form>
        <h2>Wire transfer</h2>
        <form id="wt-form"
              class="pure-form"
              action="{{ url('profile') }}"
              method="post"
              name="tform">

          <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />

          <div id="transfer-fields">
          
          <div class="fieldbox">
            <label class="fieldlabel" for="id_amount">Amount to transfer:</label>
            {{ wt_form.amount }}<!--
            --><input type="text" readonly class="currency-indicator" size="{{ currency|length }}" tabindex="-1" value="{{ currency }}">
          </div>
            
          <div class="fieldbox">
            <label class="fieldlabel" for="id_receiver">Receiver:</label>
            {{ wt_form.receiver }}
          </div>
            
          <div class="fieldbox">
            <label class="fieldlabel" for="id_receiver">Subject:</label>
            {{ wt_form.subject }}
          </div>
          
          </div>


          <input class="pure-button pure-button-primary"
                 type="submit"
                 value="Transfer!" />
        </form>
      </div>
      <p>
      </p>
    </article>
    <article>
      <h2>Transaction history</h2>
      <div id="transactions-history">
        {% if history %}
        <table class="pure-table">
          <thead>
          <tr>
            <th style="text-align:center">Date</th>
            <th style="text-align:center">Amount</th>
            <th style="text-align:center">Counterpart</th>
            <th style="text-align:center">Subject</th>
          </tr>
          </thead>
          <tbody>
          {% for item in history %}
          <tr>
            <td style="text-align:right">{{ item.date }}</td>
	    <td style="text-align:right">
              {{ item.sign }} {{ item.amount }}
            </td>
  	    <td class="text-align:left">
              {% if item.counterpart_username %}
                {{ item.counterpart_username }}
              {% endif %} (account #{{ item.counterpart }})
            </td>
	    <td class="text-align:left
              {% if item.cancelled %}
                cancelled
              {% endif %}">{{ item.subject }}
            </td>
	  </tr>
          {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p class="informational informational-fail">
          No transactions made to/from this account
        </p>
        {% endif %}
      </div>

    </article>
  </section>
{% endblock %}

talerbank/app/templates/public_accounts.html
{% extends "base.html" %}
{#
  This file is part of GNU TALER.
  Copyright (C) 2014, 2015, 2016 INRIA

  TALER is free software; you can redistribute it and/or modify it under the
  terms of the GNU Lesser General Public License as published by the Free Software
  Foundation; either version 2.1, or (at your option) any later version.

  TALER is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
  A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License along with
  TALER; see the file COPYING.  If not, see <http://www.gnu.org/licenses/>

  @author Marcello Stanisci
#}

{% block headermsg %}
  <h1 class="nav">History of public accounts</h1>
{% endblock headermsg %}

{% block content %}
  <a href="{{ url('index') }}">Back</a>
  <section id="main">
    <article>
      {% if fail_message %}
        <div class="notification">
          <p class="informational informational-fail">
            {{ hint }}
          </p>
        </div>
      {% endif %}
      {% if success_message %}
        <div class="notification">
          <p class="informational informational-ok">
            {{ hint }}
          </p>
        </div>
        {% endif %}
      <div name="accountMenu" class="pure-menu pure-menu-horizontal">
        <ul class="pure-menu-list">
        {% for account in public_accounts %}
          {% if account.account_no == selected_account.number %}
          <li class="pure-menu-item pure-menu-selected">
          {% else %}
          <li class="pure-menu-item pure-menu">
          {% endif %}
            <a href="{{ url("public-accounts", name=account.user.username) }}" class="pure-menu-link">
              {{ account.user.username }}
            </a>
          </li>
        {% endfor %}
        </ul>
      </div>

      <div class="results">
        {% if selected_account.history %}
          <table class="pure-table pure-table-striped">
            <thead>
              <th>Date</th>
              <th>Amount</th>
              <th>Counterpart</th>
              <th>Subject</th>
            </thead>
            <tbody>
            {% for entry in selected_account.history %}
            <tr>
              <td>{{entry.date}}</td>
              <td>
                {{ entry.sign }} {{ entry.amount }}
              </td>
              <td>{% if entry.counterpart_username %} {{ entry.counterpart_username }} {% endif %} (account #{{ entry.counterpart }})</td>
              <td {% if entry.cancelled %} class="cancelled" {% endif %}>
                {{ entry.subject }}
              </td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
          <div class="pages-list">
            {% if back %}
              <a
               class="page-number"
               href="{{ url("public-accounts", name=selected_account.name, page=back) }}">&lsaquo;...</a>
            {% endif %}
            {% for pagej in pages %}
              <a
               {% if pagej == current_page%}
                 class="current-page-number"
               {% else %}
                 class="page-number"
               {% endif %}
               href="{{ url("public-accounts", name=selected_account.name, page=pagej) }}">{{ pagej }}</a>
            {% endfor %}
            {% if forth %}
              <a
               class="page-number"
               href="{{ url("public-accounts", name=selected_account.name, page=forth) }}">...&rsaquo;</a>
            {% endif %}
          </div>
        {% else %}
          <p>No history for account #{{ selected_account.number }} ({{ selected_account.name}}) yet</p>
        {% endif %}
      </div>
    </article>
  </section>
{% endblock content %}